# An Example cuesubmit config file.
# It can be placed anywhere on your filesystem and referenced with
# the CUESUBMIT_CONFIG_FILE environment variable.
# If this file is not found the defaults in Constants.py will be used.

UI_NAME : "OPENCUESUBMIT"
SUBMIT_APP_WINDOW_TITLE : "OpenCue Submit"
MAYA_RENDER_CMD : "Render"
NUKE_RENDER_CMD : "nuke"
BLENDER_RENDER_CMD : "blender"
ARNOLD_RENDER_CMD : "kick"
FRAME_TOKEN : "#IFRAME#"
DEFAULT_MIN_CORES : 1
DEFAULT_MIN_CORES_MAYA : 1
DEFAULT_MIN_CORES_NUKE : 1
DEFAULT_MIN_CORES_BLENDER : 1
DEFAULT_MIN_CORES_ARNOLD : 1
DEFAULT_CHUNK : 1
DEFAULT_CHUNK_MAYA : 1
DEFAULT_CHUNK_NUKE : 1
DEFAULT_CHUNK_BLENDER : 1
DEFAULT_CHUNK_ARNOLD : 1
DEFAULT_LAYER_PREFIX : "Layer"
DEFAULT_LAYER_TYPE : "Shell"