# An Example cuesubmit config file.
# It can be placed anywhere on your filesystem and referenced with
# the CUESUBMIT_CONFIG_FILE environment variable.
# If this file is not found the defaults in Constants.py will be used.

UI_NAME: "OPENCUESUBMIT"
SUBMIT_APP_WINDOW_TITLE: "OpenCue Submit"
FRAME_TOKEN: "#IFRAME#"
DEFAULT_LAYER_PREFIX: "Layer"
DEFAULT_LAYER_TYPE: "Shell"
DEFAULT_SHOW: "testing"

LAYER_TYPE_SETTINGS:
  DEFAULT:
    CHUNK: 1
    MIN_CORES: 1
    SERVICES: ['shell']
  Maya:
    RENDER_CMD: "Render"
    CHUNK: 1
    MIN_CORES: 8
    SERVICES: ['maya']
  Nuke:
    RENDER_CMD: "nuke"
    CHUNK: 1
    MIN_CORES: 1
    SERVICES: ['nuke']
  Blender:
    RENDER_CMD:
      2.83.3: "/usr/local/blender-2.83.3/blender"
      2.83: "/usr/local/blender-2.83/blender"
      2.82a: "/usr/local/blender-2.82a/blender"
      2.9: "/usr/local/blender-2.9/blender"
    CHUNK: 1
    MIN_CORES: 16
    SERVICES: ['blender']
  Arnold:
    RENDER_CMD: "kick"
    CHUNK: 1
    MIN_CORES: 16
    SERVICES: ['arnold']
